ProjetoLivraria/Models/AutorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjetoLivraria.Models
{
    public class AutorModel
    {
        public AutorModel()
        {
            
        }

        public AutorModel(string nome)
        {
            Nome = nome;
        }

        [Required(ErrorMessage = "O campo {0} é requerido!")]
        [MaxLength(50, ErrorMessage = "O máximo de caracteres permitido para {0} é de 50!")]
        public string Nome { get; set; }
    }
}

ProjetoLivraria/Models/LivroModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjetoLivraria.Models
{
    public class LivroModel
    {
        [DisplayName("Título")]
        [Required(ErrorMessage = "O  campo {0} é requerido!")]
        [MaxLength(50, ErrorMessage = "O máximo de caracteres permitido é 50!")]
        public string Titulo { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "O  campo {0} é requerido!")]
        [MaxLength(200, ErrorMessage = "O máximo de caracteres permitido é 200!")]
        public string Descricao { get; set; }

        [DisplayName("Preço")]
        [Required(ErrorMessage = "O  campo {0} é requerido!")]
        public double Preco { get; set; } 
    }
}

ProjetoLivraria/Models/ViewModels/AutorViewModel.cs
using System.Collections.Generic;

namespace ProjetoLivraria.Models.ViewModels
{
    public class AutorViewModel
    {
        public AutorViewModel()
        {

        }

        public AutorViewModel(int id, string nome)
        {
            Id = id;
            Nome = nome;
        }

        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

ProjetoLivraria/Models/ViewModels/ListagemAutorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjetoLivraria.Models.ViewModels
{
    public class ListagemAutorViewModel
    {
        public List<AutorViewModel> ListaAutores { get; set; }
    }
}

ProjetoLivraria/Controllers/AutorController.cs
using ProjetoLivraria.Conversor;
using ProjetoLivraria.Models;
using ProjetoLivraria.Models.ViewModels;
using ProjetoLivraria.Repositories;
using System;
using System.Web.Mvc;

namespace ProjetoLivraria.Controllers
{
    public class AutorController : Controller
    {
        AutorRepository autorRepository = new AutorRepository();
        AutorConversor autorConversor = new AutorConversor();

        [HttpGet]
        public ActionResult Index()
        {
            ListagemAutorViewModel viewModel = new ListagemAutorViewModel();

            viewModel.ListaAutores = autorConversor.ObterListaAutores(autorRepository.ObterTodosAutores());

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(AutorModel autorModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    autorRepository.AdicionarNovoAutor(autorConversor.ObterEntidadeAutor(autorModel));

                    TempData["Mensagem"] = "Autor adicionado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(autorModel);
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            try
            {
                var autor = autorConversor.ObterAutorViewModel(autorRepository.ObterAutor(id));

                AutorViewModel viewModel = new AutorViewModel(autor.Id, autor.Nome);

                return View(viewModel);
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        [HttpPost]
        public ActionResult Editar(AutorViewModel autorViewModel)
        {
            try
            {
                var autor = autorConversor.ObterEntidadeAutorEdicao(autorViewModel);

                Autor autorEntidade = new Autor 
                { 
                    Id = autor.Id,
                    Nome = autor.Nome
                };

                autorRepository.EditarAutor(autorEntidade);

                TempData["Mensagem"] = "Autor alterado com sucesso!";

                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                throw;
            }
        }

        [HttpGet]
        public ActionResult Deletar(int id)
        {
            autorRepository.DeletarAutor(id);

            TempData["Mensagem"] = "Autor deletado com sucesso!";

            return RedirectToAction("Index");
        }
    }
}

ProjetoLivraria/Controllers/LivroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoLivraria.Controllers
{
    public class LivroController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjetoLivraria/Views/Autor/Adicionar.cshtml
@model ProjetoLivraria.Models.AutorModel

@{
    ViewBag.Title = "Adicionar Novo Autor";
}

<h2>Adicionar Novo Autor</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "col-md-2" })
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div> <br /> <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Salvar</button>
            <a href="@Url.Action("Index")" class="btn btn-default">Voltar</a>
        </div>
    </div>
}

ProjetoLivraria/Views/Autor/Editar.cshtml
@model ProjetoLivraria.Models.ViewModels.AutorViewModel

@{
    ViewBag.Title = "Editar Autor";
}

<h2>Editar @Model.Nome</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "col-md-2" })
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <br />
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Salvar</button>
            <a href="@Url.Action("Index")" class="btn btn-default">Voltar</a>
        </div>
    </div>
}

ProjetoLivraria/Views/Autor/Index.cshtml
@model ProjetoLivraria.Models.ViewModels.ListagemAutorViewModel

@{
    ViewBag.Title = "Autores";
}

@if (TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert" style="margin-top: 1rem;">
        @TempData["Mensagem"]
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div style="display: flex; justify-content: space-between; align-items: center;">
    <div>
        <h2>Autores</h2>
    </div>
    <div>
        <a href="@Url.Action("Adicionar")" class="btn btn-success">Adicionar</a>
    </div>
</div>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.ListaAutores.Count() > 0)
        {
            foreach (var autor in Model.ListaAutores)
            {
                <tr>
                    <td>@autor.Id</td>
                    <td>@autor.Nome</td>
                    <td>
                        <a href="@Url.Action("Editar", new { id = autor.Id })">Editar</a>
                        <a href="@Url.Action("Deletar", new { id = autor.Id })">Deletar</a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="3">Nenhum Autor Registrado!</td>
            </tr>
        }
    </tbody>
</table>

ProjetoLivraria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Livraria", "Index", "Autor", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Autores", "Index", "Autor")</li>
                    <li>@Html.ActionLink("Livros", "Index", "Livro")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema Teste de Micael Sousa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>